## In this notebook We'll understand t-test

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Single sample t-test workflow for the titanic Age column

In [3]:
train = pd.read_csv("5_train.csv").drop(columns=["Survived"])
test = pd.read_csv("5_test.csv")

In [4]:
df = pd.concat([train, test]).sample(1309)
df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
360,1252,3,"Sage, Master. William Henry",male,14.5,8,2,CA. 2343,69.5500,NaN,S
208,1100,1,"Rosenbaum, Miss. Edith Louise",female,33.0,0,0,PC 17613,27.7208,A11,C
426,427,2,"Clarke, Mrs. Charles V (Ada Maria Winfield)",female,28.0,1,0,2003,26.0000,NaN,S
347,1239,3,"Whabee, Mrs. George Joseph (Shawneene Abi-Saab)",female,38.0,0,0,2688,7.2292,NaN,C
793,794,1,"Hoyt, Mr. William Fisher",male,NaN,0,0,PC 17600,30.6958,NaN,C

In [5]:
pop = df["Age"].dropna()

In [6]:
sample_size = 25
num_sample = 20

samples = []
for i in range(num_sample):
    sample = pop.sample(n=sample_size, replace=False)  # replace=False Once an observation is selected, it cannot be selected again
    samples.append(sample)

samples = np.array(samples)
samples = samples.ravel()
samples.shape

(500,)

In [7]:
hypothesized_mean = 30

In [8]:
import scipy.stats as stats

t_statistic, p_value = stats.ttest_1samp(samples, hypothesized_mean)
print("T-Statistic: ",t_statistic)
print("P-Value: ",p_value)

T-Statistic:  -0.2798172151809232
P-Value:  0.7797336943636444

In [9]:
alpha = 0.05

if p_value < alpha:
    print("Reject the null hypothesis.")
else:
    print("Fail to reject the null hypothesis.")

Fail to reject the null hypothesis.

## Independent 2 -Sample Test

## Case Study - II 
- Average age of male is significantly greater than female

In [10]:
df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
360,1252,3,"Sage, Master. William Henry",male,14.5,8,2,CA. 2343,69.5500,NaN,S
208,1100,1,"Rosenbaum, Miss. Edith Louise",female,33.0,0,0,PC 17613,27.7208,A11,C
426,427,2,"Clarke, Mrs. Charles V (Ada Maria Winfield)",female,28.0,1,0,2003,26.0000,NaN,S
347,1239,3,"Whabee, Mrs. George Joseph (Shawneene Abi-Saab)",female,38.0,0,0,2688,7.2292,NaN,C
793,794,1,"Hoyt, Mr. William Fisher",male,NaN,0,0,PC 17600,30.6958,NaN,C

In [14]:
pop_male = df[df["Sex"] == "male"]["Age"].dropna()
pop_female = df[df["Sex"] == "female"]["Age"].dropna()

In [18]:
sample_male = pop_male.sample(50)
sample_female = pop_female.sample(50)

In [24]:
import scipy.stats as stats

t_statistic, p_value_Two_Tailed = stats.ttest_ind(sample_male, sample_female)

print("T-Statistic: ",t_statistic)
print("P-Value for Two Tailed T-Test: ",p_value_Two_Tailed)

p_value_one_tailed = p_value_Two_Tailed/2

T-Statistic:  0.12190249492442537
P-Value for Two Tailed T-Test:  0.9032258594822039

In [25]:
alpha = 0.5 

if p_value_one_tailed < alpha:
    print("Reject the null hypothesis. Average of male is significantly greater than average age of female")
else:
    print("Failed to reject the null hypothesis")

Reject the null hypothesis. Average of male is significantly greater than average age of female