## In this notebook We'll understand t-test

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Single sample t-test workflow for the titanic Age column

In [2]:
train = pd.read_csv("5_train.csv").drop(columns=["Survived"])
test = pd.read_csv("5_test.csv")

In [3]:
df = pd.concat([train, test]).sample(1309)
df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
553,554,3,"Leeni, Mr. Fahim (""Philip Zenni"")",male,22.0,0,0,2620,7.225,NaN,C
107,999,3,"Ryan, Mr. Edward",male,NaN,0,0,383162,7.750,NaN,Q
109,1001,2,"Swane, Mr. George",male,18.5,0,0,248734,13.000,F,S
741,742,1,"Cavendish, Mr. Tyrell William",male,36.0,1,0,19877,78.850,C46,S
120,121,2,"Hickman, Mr. Stanley George",male,21.0,2,0,S.O.C. 14879,73.500,NaN,S

In [4]:
pop = df["Age"].dropna()

In [5]:
sample_size = 25
num_sample = 20

samples = []
for i in range(num_sample):
    sample = pop.sample(n=sample_size, replace=False)  # replace=False Once an observation is selected, it cannot be selected again
    samples.append(sample)

samples = np.array(samples)
samples = samples.ravel()
samples.shape

(500,)

In [6]:
hypothesized_mean = 30

In [7]:
import scipy.stats as stats

t_statistic, p_value = stats.ttest_1samp(samples, hypothesized_mean)
print("T-Statistic: ",t_statistic)
print("P-Value: ",p_value)

T-Statistic:  -0.9590123341073792
P-Value:  0.3380169564131993

In [8]:
alpha = 0.05

if p_value < alpha:
    print("Reject the null hypothesis.")
else:
    print("Fail to reject the null hypothesis.")

Fail to reject the null hypothesis.

## Two Sample Independent T-test

## Case Study 2 : Average age of male is significantly greater than average age of female

In [9]:
df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
553,554,3,"Leeni, Mr. Fahim (""Philip Zenni"")",male,22.0,0,0,2620,7.225,NaN,C
107,999,3,"Ryan, Mr. Edward",male,NaN,0,0,383162,7.750,NaN,Q
109,1001,2,"Swane, Mr. George",male,18.5,0,0,248734,13.000,F,S
741,742,1,"Cavendish, Mr. Tyrell William",male,36.0,1,0,19877,78.850,C46,S
120,121,2,"Hickman, Mr. Stanley George",male,21.0,2,0,S.O.C. 14879,73.500,NaN,S

In [14]:
pop_male = df[df["Sex"] == "male"]["Age"].dropna()
pop_female = df[df["Sex"] == "female"]["Age"].dropna()

In [16]:
sample_male = pop_male.sample(50)
sample_female = pop_female.sample(50)

### H0 -> Mean age of male and female are similar
### H1 -> Mean age of male is higher than Mean age of female

In [23]:
t_statistic, p_value_two_tailed = stats.ttest_ind(sample_male, sample_female)

print("T-Statistic: ", t_statistic)
print("P-Value Two Tailed: ",p_value_two_tailed)

T-Statistic:  2.0751592136294716
P-Value Two Tailed:  0.04059152321829019

In [28]:
if t_statistic > 0:  # Male mean > Female mean
    p_value_one_tailed = p_value_two_tailed / 2
else:
    p_value_one_tailed = 1 - (p_value_two_tailed / 2)

In [29]:
alpha = 0.05

if p_value_one_tailed < alpha:
    print("Reject the null hypothesis")
else:
    print("Fail to reject the null hypothesis")

Reject the null hypothesis

In [30]:
pop_male.mean()

np.float64(30.58522796352584)

In [31]:
pop_female.mean()

np.float64(28.68708762886598)